---

# https://docs.ansible.com/ansible/latest/modules/package_module.html
- name: install dependecies
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ packages }}"
  become: yes
  become_method: "{{ become_method }}"


- debug: var=git_ref
  tags: checkout


# https://docs.ansible.com/ansible/latest/modules/tempfile_module.html
- name: create temporary build directory
  tempfile:
    state: directory
    suffix: build 
  register: temp_dir
  tags: checkout


# https://docs.ansible.com/ansible/latest/modules/git_module.html
- name: checkout git repository
  git:
    repo: 'https://github.com/OpenSMTPD/OpenSMTPD.git'
    dest: "{{ temp_dir.path }}/OpenSMTPD"
    version: "{{ git_ref }}"
  tags: checkout


# https://docs.ansible.com/ansible/latest/modules/set_fact_module.html
- set_fact: 
    build_dir: "{{ temp_dir.path }}/OpenSMTPD"
  tags: checkout


# https://docs.ansible.com/ansible/latest/modules/shell_module.html
- name: bootstrap
  shell: ./bootstrap
  args:
    chdir: "{{ build_dir }}"


# https://docs.ansible.com/ansible/latest/modules/shell_module.html
- name: configure
  shell: "./configure {{ configure_params | join (' ') }}"
  args:
    chdir: "{{ build_dir }}"


# https://docs.ansible.com/ansible/latest/modules/shell_module.html
- name: make
  shell: make
  args:
    chdir: "{{ build_dir }}"
