---

# https://docs.ansible.com/ansible/latest/modules/copy_module.html
- name: install rc script
  copy:
    src: freebsd-12/smtpd
    dest: /etc/rc.d/smtpd
    owner: root
    group: wheel
    mode: '0555'
  become: yes
  become_method: "{{ become_method }}"


# https://docs.ansible.com/ansible/latest/modules/service_module.html
- name: Stop sendmail
  service:
    name: sendmail
    state: stopped
  become: yes
  become_method: "{{ become_method }}"


# FreeBSD by default has sendmail that conflicts with opensmtpd  
# https://docs.ansible.com/ansible/latest/modules/wait_for_module.html
- name: Wait for sendmail to stop listening on port 25
  wait_for:
    port: 25
    delay: 5
    state: stopped
