---

# https://docs.ansible.com/ansible/latest/modules/shell_module.html
- name: make install
  shell: make install
  args:
    chdir: "{{ build_dir }}"
  become: yes
  become_method: "{{ become_method }}"


- name: OS specific rc/init script installation
  include: "2-{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version | lower }}.yml"


# https://docs.ansible.com/ansible/latest/modules/service_module.html
- name: Start service httpd, if not started
  service:
    name: smtpd
    state: started
  become: yes
  become_method: "{{ become_method }}"


# https://docs.ansible.com/ansible/latest/modules/wait_for_module.html
- name: Wait for opensmtpd to start listening on port 25
  wait_for:
    port: 25
    delay: 5
    state: started
